ALTER TABLE entities ADD COLUMN hp_current INT NOT NULL DEFAULT 10;
ALTER TABLE entities ADD COLUMN hp_max INT NOT NULL DEFAULT 10;
ALTER TABLE entities ADD COLUMN ap_current INT NOT NULL DEFAULT 2;
ALTER TABLE entities ADD COLUMN ap_max INT NOT NULL DEFAULT 2;
